project 'Hajj Snap.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hajj Snap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hajj Snap


 pod 'ALThreeCircleSpinner'
 pod 'EZLoadingActivity'
 pod 'Realm'
 pod 'RealmSwift'
 pod 'Alamofire'
 pod 'SwiftyJSON'
 pod 'SwiftyDrop'
 pod 'ReachabilitySwift'
 pod 'NVActivityIndicatorView'
 pod 'ReachabilitySwift'
 pod 'Toucan'
  pod 'DateToolsSwift'
 pod 'WXImageCompress'
 pod 'DZNEmptyDataSet'
pod 'ImagePicker'
pod 'RSKPlaceholderTextView'



  target 'Hajj SnapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hajj SnapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
